root: true
extends: 'standard'
rules:
  no-console: 2
  space-before-function-paren: 0
  no-multiple-empty-lines: [2, { 'max': 2 }]
  no-unused-vars: [2, { 'varsIgnorePattern': '(^_)|h', 'argsIgnorePattern': '^_' }]
  indent: [2, 2, { "SwitchCase": 0 }]
